use_frameworks!

platform :ios, '9.0'

target 'WLBaseProject_Example' do
  pod 'WLBaseProject', :path => '../'

  target 'WLBaseProject_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
